<? 
require_once('config.php'); 
require_once('/var/www/workspace/sfbackup/phpactiverecordconnection.php');
require_once('/var/www/workspace/sfbackup/sfbackup.php');

// ### This part made by me
$test = new sfbackup();
$test->getConnection($_GET['session'], $_GET['url']);
$test->backupAccount();


echo "<table border=1 >"; 
echo "<tr>"; 
echo "<td><b>Id</b></td>"; 
echo "<td><b>AccountNumber</b></td>"; 
echo "<td><b>Active  C</b></td>"; 
echo "<td><b>AnnualRevenue</b></td>"; 
echo "<td><b>BillingCity</b></td>"; 
echo "<td><b>BillingCountry</b></td>"; 
echo "<td><b>BillingPostalCode</b></td>"; 
echo "<td><b>BillingState</b></td>"; 
echo "<td><b>BillingStreet</b></td>"; 
echo "<td><b>CreatedById</b></td>"; 
echo "<td><b>CreatedDate</b></td>"; 
echo "<td><b>CustomerPriority  C</b></td>"; 
echo "<td><b>Description</b></td>"; 
echo "<td><b>Fax</b></td>"; 
echo "<td><b>Industry</b></td>"; 
echo "<td><b>IsDeleted</b></td>"; 
echo "<td><b>Jigsaw</b></td>"; 
echo "<td><b>LastActivityDate</b></td>"; 
echo "<td><b>LastModifiedById</b></td>"; 
echo "<td><b>LastModifiedDate</b></td>"; 
echo "<td><b>MasterRecordId</b></td>"; 
echo "<td><b>Name</b></td>"; 
echo "<td><b>NumberOfEmployees</b></td>"; 
echo "<td><b>NumberofLocations  C</b></td>"; 
echo "<td><b>OwnerId</b></td>"; 
echo "<td><b>Ownership</b></td>"; 
echo "<td><b>ParentId</b></td>"; 
echo "<td><b>Phone</b></td>"; 
echo "<td><b>Rating</b></td>"; 
echo "<td><b>SLAExpirationDate  C</b></td>"; 
echo "<td><b>SLASerialNumber  C</b></td>"; 
echo "<td><b>SLA  C</b></td>"; 
echo "<td><b>ShippingCity</b></td>"; 
echo "<td><b>ShippingCountry</b></td>"; 
echo "<td><b>ShippingPostalCode</b></td>"; 
echo "<td><b>ShippingState</b></td>"; 
echo "<td><b>ShippingStreet</b></td>"; 
echo "<td><b>Sic</b></td>"; 
echo "<td><b>Site</b></td>"; 
echo "<td><b>SystemModstamp</b></td>"; 
echo "<td><b>TickerSymbol</b></td>"; 
echo "<td><b>Type</b></td>"; 
echo "<td><b>UpsellOpportunity  C</b></td>"; 
echo "<td><b>Website</b></td>"; 
echo "</tr>"; 
$result = mysql_query("SELECT * FROM `accounts`") or trigger_error(mysql_error()); 
while($row = mysql_fetch_array($result)){ 
foreach($row AS $key => $value) { $row[$key] = stripslashes($value); } 
echo "<tr>";  
echo "<td valign='top'>" . nl2br( $row['id']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['AccountNumber']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Active__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['AnnualRevenue']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['BillingCity']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['BillingCountry']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['BillingPostalCode']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['BillingState']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['BillingStreet']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CreatedById']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CreatedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CustomerPriority__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Description']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Fax']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Industry']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsDeleted']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Jigsaw']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastActivityDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastModifiedById']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastModifiedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MasterRecordId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Name']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['NumberOfEmployees']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['NumberofLocations__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OwnerId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Ownership']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ParentId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Phone']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Rating']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['SLAExpirationDate__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['SLASerialNumber__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['SLA__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ShippingCity']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ShippingCountry']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ShippingPostalCode']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ShippingState']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ShippingStreet']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Sic']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Site']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['SystemModstamp']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['TickerSymbol']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Type']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['UpsellOpportunity__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Website']) . "</td>";  
echo "<td valign='top'><a href=edit.php?id={$row['id']}>Edit</a></td><td><a href=delete.php?id={$row['id']}>Delete</a></td> "; 
echo "</tr>"; 
} 
echo "</table>"; 
echo "<a href=new.php>New Row</a>"; 
?>
