<?php
include('config.php'); 
echo "<table border=1 >"; 
echo "<tr>"; 
echo "<td><b>Id</b></td>"; 
echo "<td><b>AnnualRevenue</b></td>"; 
echo "<td><b>City</b></td>"; 
echo "<td><b>Company</b></td>"; 
echo "<td><b>ConvertedAccountId</b></td>"; 
echo "<td><b>ConvertedContactId</b></td>"; 
echo "<td><b>ConvertedDate</b></td>"; 
echo "<td><b>ConvertedOpportunityId</b></td>"; 
echo "<td><b>Country</b></td>"; 
echo "<td><b>CreatedById</b></td>"; 
echo "<td><b>CreatedDate</b></td>"; 
echo "<td><b>CurrentGenerators  C</b></td>"; 
echo "<td><b>Description</b></td>"; 
echo "<td><b>Email</b></td>"; 
echo "<td><b>EmailBouncedDate</b></td>"; 
echo "<td><b>EmailBouncedReason</b></td>"; 
echo "<td><b>Fax</b></td>"; 
echo "<td><b>FirstName</b></td>"; 
echo "<td><b>Industry</b></td>"; 
echo "<td><b>IsConverted</b></td>"; 
echo "<td><b>IsDeleted</b></td>"; 
echo "<td><b>IsUnreadByOwner</b></td>"; 
echo "<td><b>Jigsaw</b></td>"; 
echo "<td><b>LastActivityDate</b></td>"; 
echo "<td><b>LastModifiedById</b></td>"; 
echo "<td><b>LastModifiedDate</b></td>"; 
echo "<td><b>LastName</b></td>"; 
echo "<td><b>LeadSource</b></td>"; 
echo "<td><b>MasterRecordId</b></td>"; 
echo "<td><b>MobilePhone</b></td>"; 
echo "<td><b>Name</b></td>"; 
echo "<td><b>NumberOfEmployees</b></td>"; 
echo "<td><b>NumberofLocations  C</b></td>"; 
echo "<td><b>OwnerId</b></td>"; 
echo "<td><b>Phone</b></td>"; 
echo "<td><b>PostalCode</b></td>"; 
echo "<td><b>Primary  C</b></td>"; 
echo "<td><b>ProductInterest  C</b></td>"; 
echo "<td><b>Rating</b></td>"; 
echo "<td><b>SICCode  C</b></td>"; 
echo "<td><b>Salutation</b></td>"; 
echo "<td><b>State</b></td>"; 
echo "<td><b>Status</b></td>"; 
echo "<td><b>Street</b></td>"; 
echo "<td><b>SystemModstamp</b></td>"; 
echo "<td><b>Title</b></td>"; 
echo "<td><b>Website</b></td>"; 
echo "</tr>"; 
$result = mysql_query("SELECT * FROM `leads`") or trigger_error(mysql_error()); 
while($row = mysql_fetch_array($result)){ 
foreach($row AS $key => $value) { $row[$key] = stripslashes($value); } 
echo "<tr>";  
echo "<td valign='top'>" . nl2br( $row['id']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['AnnualRevenue']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['City']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Company']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ConvertedAccountId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ConvertedContactId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ConvertedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ConvertedOpportunityId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Country']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CreatedById']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CreatedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CurrentGenerators__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Description']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Email']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['EmailBouncedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['EmailBouncedReason']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Fax']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['FirstName']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Industry']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsConverted']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsDeleted']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsUnreadByOwner']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Jigsaw']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastActivityDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastModifiedById']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastModifiedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastName']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LeadSource']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MasterRecordId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MobilePhone']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Name']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['NumberOfEmployees']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['NumberofLocations__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OwnerId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Phone']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['PostalCode']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Primary__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ProductInterest__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Rating']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['SICCode__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Salutation']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['State']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Status']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Street']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['SystemModstamp']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Title']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Website']) . "</td>";  
echo "<td valign='top'><a href=edit.php?id={$row['id']}>Edit</a></td><td><a href=delete.php?id={$row['id']}>Delete</a></td> "; 
echo "</tr>"; 
} 
echo "</table>"; 
echo "<a href=new.php>New Row</a>"; 
?>