<?php 
include('config.php'); 
echo "<table border=1 >"; 
echo "<tr>"; 
echo "<td><b>Id</b></td>"; 
echo "<td><b>AccountId</b></td>"; 
echo "<td><b>Amount</b></td>"; 
echo "<td><b>CampaignId</b></td>"; 
echo "<td><b>CloseDate</b></td>"; 
echo "<td><b>CreatedById</b></td>"; 
echo "<td><b>CreatedDate</b></td>"; 
echo "<td><b>CurrentGenerators  C</b></td>"; 
echo "<td><b>DeliveryInstallationStatus  C</b></td>"; 
echo "<td><b>Description</b></td>"; 
echo "<td><b>ExpectedRevenue</b></td>"; 
echo "<td><b>Fiscal</b></td>"; 
echo "<td><b>FiscalQuarter</b></td>"; 
echo "<td><b>FiscalYear</b></td>"; 
echo "<td><b>ForecastCategory</b></td>"; 
echo "<td><b>ForecastCategoryName</b></td>"; 
echo "<td><b>HasOpportunityLineItem</b></td>"; 
echo "<td><b>IsClosed</b></td>"; 
echo "<td><b>IsDeleted</b></td>"; 
echo "<td><b>IsPrivate</b></td>"; 
echo "<td><b>IsWon</b></td>"; 
echo "<td><b>LastActivityDate</b></td>"; 
echo "<td><b>LastModifiedById</b></td>"; 
echo "<td><b>LastModifiedDate</b></td>"; 
echo "<td><b>LeadSource</b></td>"; 
echo "<td><b>MainCompetitors  C</b></td>"; 
echo "<td><b>Name</b></td>"; 
echo "<td><b>NextStep</b></td>"; 
echo "<td><b>OrderNumber  C</b></td>"; 
echo "<td><b>OwnerId</b></td>"; 
echo "<td><b>Pricebook2Id</b></td>"; 
echo "<td><b>Probability</b></td>"; 
echo "<td><b>StageName</b></td>"; 
echo "<td><b>SystemModstamp</b></td>"; 
echo "<td><b>TotalOpportunityQuantity</b></td>"; 
echo "<td><b>TrackingNumber  C</b></td>"; 
echo "<td><b>Type</b></td>"; 
echo "</tr>"; 
$result = mysql_query("SELECT * FROM `opportunities`") or trigger_error(mysql_error()); 
while($row = mysql_fetch_array($result)){ 
foreach($row AS $key => $value) { $row[$key] = stripslashes($value); } 
echo "<tr>";  
echo "<td valign='top'>" . nl2br( $row['id']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['AccountId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Amount']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CampaignId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CloseDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CreatedById']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CreatedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CurrentGenerators__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['DeliveryInstallationStatus__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Description']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ExpectedRevenue']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Fiscal']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['FiscalQuarter']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['FiscalYear']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ForecastCategory']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ForecastCategoryName']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['HasOpportunityLineItem']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsClosed']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsDeleted']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsPrivate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsWon']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastActivityDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastModifiedById']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastModifiedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LeadSource']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MainCompetitors__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Name']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['NextStep']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OrderNumber__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OwnerId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Pricebook2Id']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Probability']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['StageName']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['SystemModstamp']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['TotalOpportunityQuantity']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['TrackingNumber__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Type']) . "</td>";  
echo "<td valign='top'><a href=edit.php?id={$row['id']}>Edit</a></td><td><a href=delete.php?id={$row['id']}>Delete</a></td> "; 
echo "</tr>"; 
} 
echo "</table>"; 
echo "<a href=new.php>New Row</a>"; 
?>