<?php
include('config.php'); 
echo "<table border=1 >"; 
echo "<tr>"; 
echo "<td><b>Id</b></td>"; 
echo "<td><b>AccountId</b></td>"; 
echo "<td><b>AssistantName</b></td>"; 
echo "<td><b>AssistantPhone</b></td>"; 
echo "<td><b>Birthdate</b></td>"; 
echo "<td><b>CreatedById</b></td>"; 
echo "<td><b>CreatedDate</b></td>"; 
echo "<td><b>Department</b></td>"; 
echo "<td><b>Description</b></td>"; 
echo "<td><b>Email</b></td>"; 
echo "<td><b>EmailBouncedDate</b></td>"; 
echo "<td><b>EmailBouncedReason</b></td>"; 
echo "<td><b>Fax</b></td>"; 
echo "<td><b>FirstName</b></td>"; 
echo "<td><b>HomePhone</b></td>"; 
echo "<td><b>IsDeleted</b></td>"; 
echo "<td><b>Jigsaw</b></td>"; 
echo "<td><b>Languages  C</b></td>"; 
echo "<td><b>LastActivityDate</b></td>"; 
echo "<td><b>LastCURequestDate</b></td>"; 
echo "<td><b>LastCUUpdateDate</b></td>"; 
echo "<td><b>LastModifiedById</b></td>"; 
echo "<td><b>LastModifiedDate</b></td>"; 
echo "<td><b>LastName</b></td>"; 
echo "<td><b>LeadSource</b></td>"; 
echo "<td><b>Level  C</b></td>"; 
echo "<td><b>MailingCity</b></td>"; 
echo "<td><b>MailingCountry</b></td>"; 
echo "<td><b>MailingPostalCode</b></td>"; 
echo "<td><b>MailingState</b></td>"; 
echo "<td><b>MailingStreet</b></td>"; 
echo "<td><b>MasterRecordId</b></td>"; 
echo "<td><b>MobilePhone</b></td>"; 
echo "<td><b>Name</b></td>"; 
echo "<td><b>OtherCity</b></td>"; 
echo "<td><b>OtherCountry</b></td>"; 
echo "<td><b>OtherPhone</b></td>"; 
echo "<td><b>OtherPostalCode</b></td>"; 
echo "<td><b>OtherState</b></td>"; 
echo "<td><b>OtherStreet</b></td>"; 
echo "<td><b>OwnerId</b></td>"; 
echo "<td><b>Phone</b></td>"; 
echo "<td><b>ReportsToId</b></td>"; 
echo "<td><b>Salutation</b></td>"; 
echo "<td><b>SystemModstamp</b></td>"; 
echo "<td><b>Title</b></td>"; 
echo "</tr>"; 
$result = mysql_query("SELECT * FROM `contacts`") or trigger_error(mysql_error()); 
while($row = mysql_fetch_array($result)){ 
foreach($row AS $key => $value) { $row[$key] = stripslashes($value); } 
echo "<tr>";  
echo "<td valign='top'>" . nl2br( $row['id']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['AccountId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['AssistantName']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['AssistantPhone']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Birthdate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CreatedById']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CreatedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Department']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Description']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Email']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['EmailBouncedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['EmailBouncedReason']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Fax']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['FirstName']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['HomePhone']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsDeleted']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Jigsaw']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Languages__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastActivityDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastCURequestDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastCUUpdateDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastModifiedById']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastModifiedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastName']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LeadSource']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Level__c']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MailingCity']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MailingCountry']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MailingPostalCode']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MailingState']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MailingStreet']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MasterRecordId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['MobilePhone']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Name']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OtherCity']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OtherCountry']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OtherPhone']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OtherPostalCode']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OtherState']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OtherStreet']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OwnerId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Phone']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ReportsToId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Salutation']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['SystemModstamp']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Title']) . "</td>";  
echo "<td valign='top'><a href=edit.php?id={$row['id']}>Edit</a></td><td><a href=delete.php?id={$row['id']}>Delete</a></td> "; 
echo "</tr>"; 
} 
echo "</table>"; 
echo "<a href=new.php>New Row</a>"; 
?>