<?php
include('config.php'); 
echo "<table border=1 >"; 
echo "<tr>"; 
echo "<td><b>Id</b></td>"; 
echo "<td><b>AccountId</b></td>"; 
echo "<td><b>ActivityDate</b></td>"; 
echo "<td><b>CallDisposition</b></td>"; 
echo "<td><b>CallDurationInSeconds</b></td>"; 
echo "<td><b>CallObject</b></td>"; 
echo "<td><b>CallType</b></td>"; 
echo "<td><b>CreatedById</b></td>"; 
echo "<td><b>CreatedDate</b></td>"; 
echo "<td><b>Description</b></td>"; 
echo "<td><b>IsArchived</b></td>"; 
echo "<td><b>IsClosed</b></td>"; 
echo "<td><b>IsDeleted</b></td>"; 
echo "<td><b>IsRecurrence</b></td>"; 
echo "<td><b>IsReminderSet</b></td>"; 
echo "<td><b>LastModifiedById</b></td>"; 
echo "<td><b>LastModifiedDate</b></td>"; 
echo "<td><b>OwnerId</b></td>"; 
echo "<td><b>Priority</b></td>"; 
echo "<td><b>RecurrenceActivityId</b></td>"; 
echo "<td><b>RecurrenceDayOfMonth</b></td>"; 
echo "<td><b>RecurrenceDayOfWeekMask</b></td>"; 
echo "<td><b>RecurrenceEndDateOnly</b></td>"; 
echo "<td><b>RecurrenceInstance</b></td>"; 
echo "<td><b>RecurrenceInterval</b></td>"; 
echo "<td><b>RecurrenceMonthOfYear</b></td>"; 
echo "<td><b>RecurrenceStartDateOnly</b></td>"; 
echo "<td><b>RecurrenceTimeZoneSidKey</b></td>"; 
echo "<td><b>RecurrenceType</b></td>"; 
echo "<td><b>ReminderDateTime</b></td>"; 
echo "<td><b>Status</b></td>"; 
echo "<td><b>Subject</b></td>"; 
echo "<td><b>SystemModstamp</b></td>"; 
echo "<td><b>WhatId</b></td>"; 
echo "<td><b>WhoId</b></td>"; 
echo "</tr>"; 
$result = mysql_query("SELECT * FROM `tasks`") or trigger_error(mysql_error()); 
while($row = mysql_fetch_array($result)){ 
foreach($row AS $key => $value) { $row[$key] = stripslashes($value); } 
echo "<tr>";  
echo "<td valign='top'>" . nl2br( $row['id']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['AccountId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ActivityDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CallDisposition']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CallDurationInSeconds']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CallObject']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CallType']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CreatedById']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['CreatedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Description']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsArchived']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsClosed']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsDeleted']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsRecurrence']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['IsReminderSet']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastModifiedById']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['LastModifiedDate']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['OwnerId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Priority']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['RecurrenceActivityId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['RecurrenceDayOfMonth']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['RecurrenceDayOfWeekMask']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['RecurrenceEndDateOnly']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['RecurrenceInstance']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['RecurrenceInterval']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['RecurrenceMonthOfYear']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['RecurrenceStartDateOnly']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['RecurrenceTimeZoneSidKey']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['RecurrenceType']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['ReminderDateTime']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Status']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['Subject']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['SystemModstamp']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['WhatId']) . "</td>";  
echo "<td valign='top'>" . nl2br( $row['WhoId']) . "</td>";  
echo "<td valign='top'><a href=edit.php?id={$row['id']}>Edit</a></td><td><a href=delete.php?id={$row['id']}>Delete</a></td> "; 
echo "</tr>"; 
} 
echo "</table>"; 
echo "<a href=new.php>New Row</a>"; 
?>